<title><?=$title?></title>
<meta name="description" content="<?=$description?>" />
<meta name="robots" content="noindex,nofollow" />
<meta content="text/html; charset=iso-8859-1" http-equiv="Content-Type" />
<link href="<?=$urlSkin?>css/core.css" rel="stylesheet" type="text/css" />
<link href="<?=$urlSkin?>css/site.css" rel="stylesheet" type="text/css" />
<? include($pathCommons."includes/literales.phtml");?>	
<script type="text/javascript" language="javascript">
	var urlAdmin = '<?= URL_ADMIN ?>/';
	var urlImgAdmin = '<?= URL_IMG_ADMIN ?>/';
</script>	
<script src="<?=URL_LIBJS?>prototype.js" type="text/javascript" language="javascript" ></script>
<script src="<?=$urlCommons?>js/actions.js" type="text/javascript" language="javascript"></script>
<script src="<?=$urlCommons?>js/edicion.js" type="text/javascript" language="javascript"></script>