<script language="javascript">
		<!--
		var gcMsg_mensaje = '<?= _("Informa el titulo")?>';
		var gcMsg_galeriaupload = '<?= _("Informa a qu&eacute; galer&iacute;a pertenece la foto")?>';
		var gcMsg_email= '<?= _("> El formato del email no es correcto.<br>")?>';
		var gcMsg_usuario= '<?= _("> El usuario es obligatorio.<br>")?>';
		var gcMsg_password= '<?= _("> El password es obligatorio.<br>")?>';
		var gcMsg_nivel= '<?= _("> El nivel de acceso es obligatorio.<br>")?>';
		var gcMsg_nombre= '<?= _("> El nombre es obligatorio.<br>")?>';
		var gcMsg_modulo= '<?= _("> El modulo es obligatorio.<br>")?>';
		var gcMsg_direccion = '<?= _("> La direcci&oacute;n es obligatoria.<br>")?>';
		var gcMsg_fechainicio= '<?= _("> La fecha de inicio es obligatoria.<br>")?>';
		var gcMsg_fechafin= '<?= _("> La fecha de fin es obligatoria.<br>")?>';
		var gcMsg_cartel= '<?= _("> El cartel es obligatorio.<br>")?>';
		var gcMsg_descripcion= '<?= _("> La descripcion es obligatoria.<br>")?>';
		var gcMsg_url= '<?= _("> La url es obligatoria.<br>")?>';
		var gcMsg_titulo= '<?= _("> El titulo es obligatoria.<br>")?>';
		var gcMsg_idioma= '<?= _("> El idioma es obligatorio.<br>")?>';
		var gcMsg_layout= '<?= _("> La plantilla es obligatoria.<br>")?>';
		var gcMsg_texto= '<?= _("> El texto es obligatorio.<br>")?>';
		var gcMsg_doc= '<?= _("> Hay que subir el documento.<br>")?>';
		var gcMsg_img= '<?= _("> Hay que subir la imagen.<br>")?>';
		var gcMsg_espacio= '<?= _("> Hay que elegir un espacio.<br>")?>';
		var gcMsg_dia= '<?= _("> Hay que elegir un dia.<br>")?>';
		var gcMsg_espacio= '<?= _("> Hay que elegir una hora.<br>")?>';
		var gcMsg_fichatecnica= '<?= _("> Hay que informar la ficha tecnica.<br>")?>';
		var gcMsg_sinopsis= '<?= _("> Hay que informar la sinopsis.<br>")?>';
		var gcMsg_ok= '<?= _("Todo ha ido bien")?>';
		var gcMsg_ko= '<?= _("Ooops algo no ha ido bien!")?>';
		var gcMsg_confirmdelete= '<?= _("Estas segur@ de eliminar")?>';
		var gcMsg_confirmdeleteimg= '<?= _("Estas segur@ de cambiar la imagen")?>';
		var gcMsg_url= '<?= _("El formato del enlace no es correcto")?>';
		var gcMsg_revisa= '<?= _("Revisa los siguientes errores")?>';
		//-->
		</script>