<meta content="text/html; charset=iso-8859-1" http-equiv="Content-Type" />
<!--  <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />-->
<meta http-equiv="Cache-control" content="public">
<title><?= $edicion->nombre ?> &mdash; <?= $title ?></title>
<meta content="Lavapi&eacute;s de Cine" name="Generator" />
<meta content="Muestra, Cine, Lavapi&eacute;s, Cultura, Madrid, Autoproducciones, Proyecci&oacute;n, Solar" name="keywords" />
<meta content="Lavapi&eacute;s de cine" name="Origen" />
<meta content="<?=$description?>" name="Description" />
<meta content="Lavapi&eacute;s de cine" name="Author" />
<meta content="Lavapi&eacute;s, Madrid" name="Locality" />
<link href="<?=$urlCommons?>css/lightbox.css" rel="stylesheet" type="text/css" />
<link rel="icon" href="<?=URL_IMG?>logo_lavapies_firma.JPG"/>
<script src="<?= URL_LIBJS?>prototype.js" type="text/javascript" language="javascript"></script>
<script src="<?= URL_LIBJS?>scriptaculous.js?load=effects" type="text/javascript" language="javascript"></script>
<script src="<?= URL_LIBJS?>lightboxXL.js" type="text/javascript"></script>
<script type="text/javascript" language="javascript">
	var urlWWW = '<?= BASE_URL ?>/';
</script>
<?	include_once($pathCommons. "google-analytics.html"); ?>