<div id="idiomas">
	<form name="formLang" id="formLang" action="<?=BASE_URL?>/bases" method="post">
		<input type="hidden" name="lang" id="lang" value="<?=$lang?>"/>
		<?  
			$count = 0;
			foreach ($langs as $language) { 
				if($lang==$language->lang){
					 echo $language->nombre;
				} else { ?>
					<a id='lang-<?=$language->lang?>' href="#"><?=$language->nombre?></a>
				<?}
				if ($count < count($langs)-1){
					echo "  |  ";
				}
				$count++;
		}?>
	</form>
</div>	