<div id="proyecciones">
	<span class="titleProyecciones"><a href="<?= $this->_baseUrl?>proyecciones">Proyecciones</a></span><br>
	Junio 2012 - Julio 2012
	<div id='calendario'>
		<?=	UtilPagina::calendario($this->_anyo, $fechaInicio, $fechaFin, BASE_URL."/proyecciones") ?>
	</div>	
</div>
<div id="textos">
	<ul>
		<li><a href="<?= URL_DOC?>programa-de-mano2012.pdf"><strong>Programa de mano</strong></a> <span class="mini">(PDF 1.9 MB)</span></li>
	</ul>
</div>
<div id="textos">
	<ul>
		<li><a href="<?= $this->_baseUrl?>agradecimientos">Agradecimientos</a></li>
	</ul>
</div>
<div id="textos">
	<ul>
		<li class="mayo"><span><a href="<?= $this->_baseUrl?>paisajes-activos">depende de nosotrxs vivirlo</a><br><a href="http://lavapiesdecine.net/en-la-plaza">En la plaza</a></span></li>
	</ul>
</div>
<div id="logos">
	<ul>
		<li class="facebook"><span><a target="_blank" href="http://facebook.com/lavapiesdecine">facebook.com/lavapiesdecine</a></span></li>
		<li class="twitter"><span><a target="_blank" href="http://twitter.com/lavapiesdecine">twitter.com/lavapiesdecine</a></span></li>
		<li class="blip"><span><a target="_blank" href="http://blip.tv/lavapiesdecine">blip.tv/lavapiesdecine</a></span></li>
		<li class="mail"><span><a href="<?= $this->_baseUrl?>contacta">escr&iacute;benos</a></span></li>
	</ul>
</div>
<div id="licencia">
	<p><span class="titleProyecciones">Licencia</span><br>
	<span class="mini">Los contenido generados por la Muestra de Cine de Lavapi&eacute;s estan liberados con la licencia <a href="http://creativecommons.org/licenses/by-sa/3.0/es/"><strong>Creative commons BY-SA</strong></a>.<br>
	Las sinopsis y los carteles de la pel&iacute;culas son propiedad de sus autores.</span>
	
	<p><span class="titleProyecciones">Software</span><br>
	<a href="<?= $this->_baseUrl?>filmfestCMS">filmfestCMS</a></p>
	
	<p><span class="titleProyecciones">Hosting</span><br>
	<a href="http://xsto.info" target="_blank"><img src="<?= URL_LOGO ?>www/xsto.info.png" /></a></p>
</div>