<form id='form_galeria' name='form_galeria' method='post' >
	<input name='id' id='id' value='<?= $this->_id ?>' type='hidden'/>
	<p><label><?= _("Galer&iacute;a de im&aacute;genes")?></label>
	<input name='id_nombre' id='id_nombre' value="<?= $nombre ?>" /></p>
	<p><label><?= _("Descripci&oacute;n")?> <span class="small"><?= _("no obligatorio")?> </span></label>
	<input name='id_descripcion' id='id_descripcion' value="<?= $descripcion ?>" /></p>
	<p><input class="boton-enviar" id='b_galeria' name='b_galeria' type="button" value="<?=_("aceptar")?>" /></p>	
</form>
	