<form id='form_lang' name='form_lang' method='post' >
	<input name='id' id='id' value='<?= $this->_id ?>' type='hidden'/>
	<p class="micro"><label><?= _("Nombre")?></label>
	<input name='id_nombre' id='id_nombre' value="<?= $nombre ?>" /></p>
	<p class="micro"><label><?= _("C&oacute;digo")?></label>
	<input name='id_codigo' id='id_codigo' value="<?= $codigo ?>" /></p>
	<p class="micro"><label><?= _("Codificaci&oacute;n")?></label>
	<input name='id_codificacion' id='id_codificacion' value="<?= $codificacion ?>" /></p>
	<p><input class="boton-enviar" id='b_lang' name='b_lang' type="button" value="<?=_("aceptar")?>" /></p>	
</form>