<!-- TinyMCE -->
<script src="<?=URL_LIBJS?>tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
	tinyMCE.init({
		//mode : "textareas",
		//mode : "exact",
		mode : "specific_textareas",
        editor_selector : "mceEditor",
		theme : "advanced",
		theme_advanced_buttons1 : "bold,italic,underline,separator,link,unlink,separator,image,media,separator,code,fullscreen",
		theme_advanced_buttons2 : "",
		theme_advanced_buttons3 : "",
		plugins : "fullscreen"
	});
</script>
<!-- /TinyMCE -->

<!-- cartel -->
<? if(empty($img)){?>
	<iframe height='100px' width='100px'  id='frame_imagen' name='frame_imagen' class='frame oculto' scrolling='no' src="<?=URL_ADMIN?>/pelicula/upload" ></iframe>
<? }?>
<div id="div-img" class="<?= $classUpload ?>">
	<?if(!empty($img)){?>
		<img width="100px" height="100px" src="<?= $img?>" id="imagen_uploaded" />
		<a href="#" id="change-img" class="<?= $urlPagina."-".$this->_id ?>"><?= _("Cambiar im&aacute;gen")?></a>
	<?} else { ?>
		<form enctype="multipart/form-data" method='post' id="form_imagen" name="form_imagen" action="<?=URL_ADMIN?>/pelicula/upload" target="frame_imagen">
			<p><?=_("subir im&aacute;gen")?><br>(jpg, gif, png)</p>
			<input name='id_nombre' id='id_nombre' value='<?=$titulo?>' type='hidden'/>
			<input name='galeria' id='galeria' value='<?=$this->_anyo?>' type='hidden'/>
			<input name='id_pelicula' id='id_pelicula' value='<?=$this->_id?>' type='hidden'/>
			<input type="file" name="imagen" id="imagen"  /><br>
		</form>
	<? } ?>	
</div>
<!-- cartel -->

<div id="div-img-info">
	<form id='formPelicula' name='formPelicula' method='post'>
		<input name='id' id='id' value='<?= $this->_id ?>' type='hidden'/>
		<input name='id_muestra' id='id_muestra' value='<?=$this->_anyo?>' type='hidden'/>
		<input value='<?=$idImgPelicula?>' name='file_imagen' id='file_imagen' type='hidden' />
		<input type="hidden" value='' name='id_descarga' id='id_descarga' />
		
		<p><label><?=_("T&iacute;tulo de la pel&iacute;cula")?></label><input  value='<?=$titulo?>' name='titulo' id='titulo' /></p>
		<p><label><?=_("Proyecci&oacute;n")?> <span class="small"><?=_("si no la encuentras")?>: <a href="<?=URL_ADMIN?>/proyeccion"><?=_("alta de proyecciones")?></a></span></label>
		<select id='id_proyeccion' name='id_proyeccion'>
			<?= UtilPagina::getOptions($proyecciones, $idProyeccion) ?>
		</select></p>
		<p><label><?=_("Agradecimientos")?> <span class="small"><?=_("si no la encuentras")?>: <a href="<?=URL_ADMIN?>/agradecimiento"><?=_("agradecimientos")?></a></span></label>
			<select id='id_donante' name='id_donante'>
			<?= UtilPagina::getOptions($agradecimientos, $idAgradecimiento) ?>
			</select></p>
		
		
		<p class="break"><label><?=_("Trailer streaming")?> <span class="small">(youtube, blip.tv, dailymotion ...)</span></label>
		<input value='<?=$url?>' name='id_enlace' id='id_enlace' /></p>
		
		<p><label><?=_("Licencia")?> <span class="small"></span></label>
		<select id='id_licencia' name='id_licencia'>
			<?= UtilPagina::getOptions($licencias, $idLicencia, false) ?>
		</select></p>
		
		<p><label><?=_("Presentaci&oacute;n")?> <span class="small"><?=_("si hay debate previo, presenta la directora, si nos hace ilusi&oacute;n...")?></span></label> 
		<textarea id="id_propio" name="id_propio" rows='2'><?= $txtPresentacion ?></textarea>
		</p>
				
		<p><label><?=_("Ficha t&eacute;cnica")?> </label>
			<textarea id="id_ficha" name="id_ficha" class="mceEditor"><?= $fichaTecnica ?></textarea>
		</p>
		
		<p><label><?=_("Sinopsis")?> </label>
			<textarea id="id_sinopsis" name="id_sinopsis" class="mceEditor"><?= $sinopsis ?></textarea>
		</p>	
		
		<p class="boton-enviar"><input id='b_pelicula' name='b_pelicula' type="button" value="<?=_("aceptar")?>"></p>	
	</form>
</div>