<!-- TinyMCE -->
<script src="<?=URL_LIBJS?>tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
	tinyMCE.init({
		//mode : "textareas",
		//mode : "exact",
		mode : "specific_textareas",
        editor_selector : "mceEditor",
		theme : "advanced",
		theme_advanced_buttons1 : "bold,italic,underline,separator,link,unlink,separator,image,media,separator,code,fullscreen",
		theme_advanced_buttons2 : "",
		theme_advanced_buttons3 : "",
		plugins : "fullscreen"
	});
</script>
<!-- /TinyMCE -->
<form id='form_texto' name='form_texto' method='post'>
	<input name='id' id='id' value='<?= $this->_id ?>' type='hidden'/>
	<input name='id_muestra' id='id_muestra' value='<?= $this->_anyo ?>' type='hidden'/>
	
	<p><label> <?=_("T&iacute;tulo")?></label>
	<input value='<?=$titulo?>' name='id_titulo' id='id_titulo'/></p>
	
	<p><label><?=_("Idioma")?> </label>
	<select name='lang' id='lang' style="width:200px">
	<?= UtilPagina::getOptions($langs, $lang) ?>
	</select>
										
	<p><label><?=_("Texto")?></label>
		<textarea id="texto" name="texto" class="mceEditor" rows="20"><?= $texto?></textarea></p>
	
	<p class="mini break"> <label><?= _("Añadir galer&iacute;a de im&aacute;genes/v&iacute;deos")?></label> 
		<select name="id_galeria" id="id_galeria">
			<?= UtilPagina::getOptions($galerias, $idGaleria) ?>
		</select> 
	</p>
	
	<p class="boton-enviar"><input id='b_texto' name='b_texto' type="button" value="<?=_("aceptar")?>"></p>	
</form>