<div id="pie">	
	<p class="logo-pie">
			<a href="http://xsto.info" target="_blank"><img src="<?=$urlSkin?>img/xstoinfo.png" /><span>hosting: xsto.info</span></a><a href="http://facebook.com/lavapiesdecine" target="_blank"><img src="<?=$urlSkin?>img/facebook.png" /><span>facebook.com/lavapiesdecine</span></a>
			<a href="http://twitter.com/lavapiesdecine" target="_blank"><img src="<?=$urlSkin?>img/twitter.png" /><span>twitter.com/lavapiesdecine</span></a><a href="http://blip.tv/lavapiesdecine" target="_blank"><img src="<?=$urlSkin?>img/blip.png" /><span>blip.tv/lavapiesdecine</span></a>
	</p>
</div>
<strong>unbarrio</strong>muchosmundos<strong>unmundo</strong>muchosbarrios
<div class="footer-main-content"></div>