<div id="pie">	
	<p><?=_("Ediciones anteriores :")?> 
		<a href="http://www.lavapiesdecine.net/2011" target="_blank">2011</a>&nbsp;&nbsp;
		<a href="http://www.lavapiesdecine.net/2010" target="_blank">2010</a>&nbsp;&nbsp;
		<a href="http://www.lavapiesdecine.net/2009" target="_blank">2009</a>&nbsp;&nbsp;
		<a href="http://www.lavapiesdecine.net/2008" target="_blank">2008</a>&nbsp;&nbsp;
		<a href="http://www.lavapiesdecine.net/2007" target="_blank">2007</a>&nbsp;&nbsp;   
	   <a href="http://www.lavapiesdecine.net/2006" target="_blank">2006</a>&nbsp;&nbsp;
	   <a href="http://www.lavapiesdecine.net/2005" target="_blank">2005</a>&nbsp;&nbsp;
	   <a href="http://www.lavapiesdecine.net/2004" target="_blank">2004</a>&nbsp;&nbsp;
		|&nbsp;&nbsp;<?=_("contacta con nosotr*s en")?> <a href='mailto:muestra@lavapiesdecine.net'>muestra@lavapiesdecine.net</a>				   
	</p>
	<p class="logo-pie">
			<a href="http://xsto.info" target="_blank"><img src="<?=$urlSkin?>img/xstoinfo.png" /><span>hosting: xsto.info</span></a><a href="http://facebook.com/lavapiesdecine" target="_blank"><img src="<?=$urlSkin?>img/facebook.png" /><span>facebook.com/lavapiesdecine</span></a>
			<a href="http://twitter.com/lavapiesdecine" target="_blank"><img src="<?=$urlSkin?>img/twitter.png" /><span>twitter.com/lavapiesdecine</span></a><a href="http://blip.tv/lavapiesdecine" target="_blank"><img src="<?=$urlSkin?>img/blip.png" /><span>blip.tv/lavapiesdecine</span></a>
	</p>
</div>
<strong>unbarrio</strong>muchosmundos<strong>unmundo</strong>muchosbarrios
<div class="footer-main-content"></div>