<?= $txt ?>
<? foreach ($peliculas as $pelicula) { ?>	
		<div class='atp_muestra'>
			<a title='<?=$pelicula->titulo ?>' href='<?=BASE_URL."/pelicula/$pelicula->id/".Util::stripAccents($pelicula->titulo)?>'>
			<img src='<?=$pelicula->cartel?>' title='<?=$pelicula->titulo?>' alt='<?=$pelicula->titulo?>' /></a>
			<br>
			<strong><?=$pelicula->titulo?></strong></br>
			<span><?=$pelicula->autor?></span>
		</div>
<? } ?>	